### ISSUE TITLE
feature: Adição de LazyLoading para Imagens do Blog

### ISSUE THREAD

**Issue by manuelbento19** [euotiniel/euotiniel.com#9]
Atualmente, o carregamento das imagens do blog pode deixar a página lenta, principalmente em dispositivos móveis. Gostaria de ajudar a melhorar isso implementando o LazyLoading para carregar as imagens apenas quando necessário.

### Tarefas

- [x] #10
- [x] Testar em diferentes dispositivos e navegadores para garantir que funcione corretamente.
 
Notas
Esta melhoria pode ajudar a tornar a sua secção de blog mais rápido e melhorar a experiência do usuário.
Estou disponível para discutir qualquer dúvida ou problema durante a implementação.

**Comment by manuelbento19** [comment]
Gostaria de realçar que já estou trabalhando nisso.

**Comment by euotiniel** [comment]
@manuelbento19 obrigado pela contribuição!

**Comment by manuelbento19** [comment]
Foi um prazer... Espero puder contribuir mais vezes, até porque a gente aprende bastante com o projeto dos outros.
Queria também poder lhe parabenizar pela simplicidade no projeto e por indiretamente ter demonstrado sobre a praticidade e real necessidade de um Dev ter um portifólio, nem que for um simples, como o seu. 
Queria também lhe parabenizar pela organização no código 💪🏽💻
Keep Working

**Comment by euotiniel** [comment]
Muito obrigado pelas palavras, você é o cara!
